const stockdata = {
  AAPL: {
    data: {
      symbol: "AAPL:NASDAQ",
      name: "Apple Inc",
      type: "stock",
      price: 169.58,
      open: 169.59,
      high: 170.39,
      low: 168.95,
      volume: 42104826,
      previous_close: 168.82,
      change: 0.76,
      change_percent: 0.4502,
      pre_or_post_market: 169.47,
      pre_or_post_market_change: -0.11,
      pre_or_post_market_change_percent: -0.0649,
      last_update_utc: "2024-04-06 00:30:00",
      country_code: "US",
      exchange: "NASDAQ",
      exchange_open: "2024-04-05 09:30:00",
      exchange_close: "2024-04-05 16:00:00",
      timezone: "America/New_York",
      utc_offset_sec: -14400,
      currency: "USD",
      about:
        "Apple Inc. is an American multinational corporation and technology company headquartered in Cupertino, California, in Silicon Valley. It designs, develops, and sells consumer electronics, computer software, and online services. Devices include the iPhone, iPad, Mac, Apple Watch, Vision Pro, and Apple TV; operating systems include iOS, iPadOS, and macOS; and software applications and services include iTunes, iCloud, Apple Music, and Apple TV+.\nFor most of 2011 to 2024, Apple became the world's largest company by market capitalization until Microsoft assumed the position in January 2024. In 2022, Apple was the largest technology company by revenue, with US$394.3 billion. As of 2023, Apple was the fourth-largest personal computer vendor by unit sales, the largest manufacturing company by revenue, and the largest vendor of mobile phones in the world. It is one of the Big Five American information technology companies, alongside Alphabet, Amazon, Meta, and Microsoft.\nApple was founded as Apple Computer Company on April 1, 1976, to produce and market Steve Wozniak's Apple I personal computer. The company was incorporated by Wozniak and Steve Jobs in 1977.",
      year_low: 159.78,
      year_high: 199.62,
      primary_exchange: "NASDAQ",
      company_website: "http://www.apple.com/",
      company_country_code: "US",
      company_country: "United States",
      company_state: "California",
      company_city: "Cupertino",
      company_street_address: "One Apple Park Way",
      company_ceo: "Tim Cook",
      company_employees: 161000,
      company_cdp_score: "A-",
      company_founded_date: "1976-04-01",
      company_cdp_url: "https://www.cdp.net/en/responses/865",
      avg_volume: 56181350,
      company_pe_ratio: 26.3858,
      company_market_cap: 2618632342874.908,
      company_dividend_yield: 0.5661,
      wikipedia_url: "https://en.wikipedia.org/wiki/Apple_Inc.",
      google_mid: "/m/07zmbvf",
    },
  },

  MSFT: {
    data: {
      symbol: "MSFT:NASDAQ",
      name: "Microsoft Corp",
      type: "stock",
      price: 425.52,
      open: 420.01,
      high: 426.51,
      low: 418.32,
      volume: 16554761,
      previous_close: 417.88,
      change: 7.64,
      change_percent: 1.8283,
      pre_or_post_market: 425.48,
      pre_or_post_market_change: -0.04,
      pre_or_post_market_change_percent: -0.0094,
      last_update_utc: "2024-04-06 00:30:00",
      country_code: "US",
      exchange: "NASDAQ",
      exchange_open: "2024-04-05 09:30:00",
      exchange_close: "2024-04-05 16:00:00",
      timezone: "America/New_York",
      utc_offset_sec: -14400,
      currency: "USD",
      about:
        "Microsoft Corporation is an American multinational corporation and technology company headquartered in Redmond, Washington. Microsoft's best-known software products are the Windows line of operating systems, the Microsoft 365 suite of productivity applications, and the Edge web browser. Its flagship hardware products are the Xbox video game consoles and the Microsoft Surface lineup of touchscreen personal computers. Microsoft ranked No. 14 in the 2022 Fortune 500 rankings of the largest United States corporations by total revenue; and it was the world's largest software maker by revenue in 2022 according to Forbes Global 2000. It is considered one of the Big Five American information technology companies, alongside Alphabet, Amazon, Apple, and Meta.\nMicrosoft was founded by Bill Gates and Paul Allen on April 4, 1975, to develop and sell BASIC interpreters for the Altair 8800. It rose to dominate the personal computer operating system market with MS-DOS in the mid-1980s, followed by Windows. The company's 1986 initial public offering and subsequent rise in its share price created three billionaires and an estimated 12,000 millionaires among Microsoft employees.",
      year_low: 275.37,
      year_high: 430.82,
      primary_exchange: "NASDAQ",
      company_website: "http://www.microsoft.com/",
      company_country_code: "US",
      company_country: "United States",
      company_state: "Washington",
      company_city: "Redmond",
      company_street_address: "One Microsoft Way",
      company_ceo: "Satya Nadella",
      company_employees: 221000,
      company_cdp_score: "A",
      company_founded_date: "1975-04-04",
      company_cdp_url: "https://www.cdp.net/en/responses/11930",
      avg_volume: 16911151,
      company_pe_ratio: 38.484,
      company_market_cap: 3161799045086.792,
      company_dividend_yield: 0.705,
      wikipedia_url: "https://en.wikipedia.org/wiki/Microsoft",
      google_mid: "/m/07zln_9",
    },
  },
  AMZN: {
    data: {
      symbol: "AMZN:NASDAQ",
      name: "Amazon.com Inc",
      type: "stock",
      price: 185.07,
      open: 182.38,
      high: 186.27,
      low: 181.97,
      volume: 42373992,
      previous_close: 180,
      change: 5.07,
      change_percent: 2.8167,
      pre_or_post_market: 185.2,
      pre_or_post_market_change: 0.13,
      pre_or_post_market_change_percent: 0.0702,
      last_update_utc: "2024-04-06 00:30:00",
      country_code: "US",
      exchange: "NASDAQ",
      exchange_open: "2024-04-05 09:30:00",
      exchange_close: "2024-04-05 16:00:00",
      timezone: "America/New_York",
      utc_offset_sec: -14400,
      currency: "USD",
      about:
        'Amazon.com, Inc., doing business as Amazon, is an American multinational technology company, engaged in e-commerce, cloud computing, online advertising, digital streaming, and artificial intelligence. It is considered one of the Big Five American technology companies; the other four are Alphabet, Apple, Meta, and Microsoft.\nAmazon was founded on July 5, 1994, by Jeff Bezos in Bellevue, Washington. The company originally started as an online marketplace for books but gradually expanded its offerings to include a wide range of product categories. This diversification led to it being referred to as "The Everything Store".\nThe company has multiple subsidiaries, including Amazon Web Services, providing cloud computing, Zoox, a self-driving car division, Kuiper Systems, a satellite Internet provider, and Amazon Lab126, a computer hardware R&D provider. Other subsidiaries include Ring, Twitch, IMDb, and Whole Foods Market. Its acquisition of Whole Foods in August 2017 for US$13.4 billion substantially increased its market share and presence as a physical retailer.',
      year_low: 97.705,
      year_high: 186.27,
      primary_exchange: "NASDAQ",
      company_website: "http://www.aboutamazon.com/",
      company_country_code: "US",
      company_country: "United States",
      company_state: "Washington",
      company_city: "Seattle",
      company_street_address: "410 Terry Avenue North",
      company_ceo: "Andy Jassy",
      company_employees: 1525000,
      company_founded_date: "1994-07-05",
      avg_volume: 30111211,
      company_pe_ratio: 63.821,
      company_market_cap: 1922392492679.443,
      wikipedia_url: "https://en.wikipedia.org/wiki/Amazon_(company)",
      google_mid: "/m/07zl90k",
    },
  },
  NVDA: {
    data: {
      symbol: "NVDA:NASDAQ",
      name: "NVIDIA Corp",
      type: "stock",
      price: 880.08,
      open: 868.66,
      high: 884.81,
      low: 859.26,
      volume: 39967846,
      previous_close: 859.05,
      change: 21.03,
      change_percent: 2.4481,
      pre_or_post_market: 880.49,
      pre_or_post_market_change: 0.41,
      pre_or_post_market_change_percent: 0.0466,
      last_update_utc: "2024-04-06 00:30:00",
      country_code: "US",
      exchange: "NASDAQ",
      exchange_open: "2024-04-05 09:30:00",
      exchange_close: "2024-04-05 16:00:00",
      timezone: "America/New_York",
      utc_offset_sec: -14400,
      currency: "USD",
      about:
        "Nvidia Corporation is an American multinational corporation and technology company headquartered in Santa Clara, California, and incorporated in Delaware. It is a software and fabless company which designs and supplies graphics processing units, application programming interfaces for data science and high-performance computing as well as system on a chip units for the mobile computing and automotive market. Nvidia is also a dominant supplier of artificial intelligence hardware and software.\nNvidia's professional line of GPUs are used for edge-to-cloud computing and in supercomputers and workstations for applications in such fields as architecture, engineering and construction, media and entertainment, automotive, scientific research, and manufacturing design. Its GeForce line of GPUs are aimed at the consumer market and are used in applications such as video editing, 3D rendering and PC gaming. In the second quarter of 2023, Nvidia had a market share of 80.2% in the discrete desktop GPU market. The company expanded its presence in the gaming industry with the introduction of the Shield Portable, Shield Tablet and Shield TV, as well as its cloud gaming service GeForce Now.",
      year_low: 262.2,
      year_high: 974,
      primary_exchange: "NASDAQ",
      company_website: "http://www.nvidia.com/",
      company_country_code: "US",
      company_country: "United States",
      company_state: "California",
      company_city: "Santa Clara",
      company_street_address: "2788 San Tomas Expressway",
      company_ceo: "Jensen Huang",
      company_employees: 29600,
      company_cdp_score: "B",
      company_founded_date: "1993-04-undefined",
      company_cdp_url: "https://www.cdp.net/en/responses/13604",
      avg_volume: 48728355,
      company_pe_ratio: 73.754,
      company_market_cap: 2200200042724.6094,
      company_dividend_yield: 0.0182,
      wikipedia_url: "https://en.wikipedia.org/wiki/Nvidia",
      google_mid: "/m/07zllzd",
    },
  },
  META: {
    data: {
      symbol: "META:NASDAQ",
      name: "Meta Platforms Inc",
      type: "stock",
      price: 527.34,
      open: 516.855,
      high: 530.7,
      low: 514.4099,
      volume: 19263265,
      previous_close: 510.92,
      change: 16.42,
      change_percent: 3.2138,
      pre_or_post_market: 528,
      pre_or_post_market_change: 0.66,
      pre_or_post_market_change_percent: 0.1252,
      last_update_utc: "2024-04-06 00:30:00",
      country_code: "US",
      exchange: "NASDAQ",
      exchange_open: "2024-04-05 09:30:00",
      exchange_close: "2024-04-05 16:00:00",
      timezone: "America/New_York",
      utc_offset_sec: -14400,
      currency: "USD",
      about:
        'Meta Platforms, Inc., doing business as Meta, and formerly named Facebook, Inc., and TheFacebook, Inc., is an American multinational technology conglomerate based in Menlo Park, California. The company owns and operates Facebook, Instagram, Threads, and WhatsApp, among other products and services. Meta ranks among the largest American information technology companies, alongside other Big Five corporations Alphabet, Amazon, Apple, and Microsoft. The company was ranked #31 on the Forbes Global 2000 ranking in 2023.\nMeta has also acquired Oculus, Mapillary, CTRL-Labs, and a 9.99% stake in Jio Platforms; the company additionally endeavored into non-VR hardware, such as the discontinued Meta Portal smart displays line and presently partners with Luxottica through the Ray-Ban Stories series of smart glasses. Despite endeavors into hardware, the company relies on advertising for a vast majority of its revenue, amounting to 97.8 percent in 2023.\nParent company Facebook, Inc. rebranded as Meta Platforms, Inc. on October 28, 2021, to "reflect its focus on building the metaverse", an integrated environment linking the company\'s products and services.',
      year_low: 207.13,
      year_high: 530.7,
      primary_exchange: "NASDAQ",
      company_website: "https://www.meta.com/",
      company_ceo: "Mark Zuckerberg",
      company_employees: 67317,
      company_cdp_score: "B",
      company_founded_date: "2004-02-undefined",
      company_cdp_url: "https://www.cdp.net/en/responses/40556",
      avg_volume: 11578790,
      company_pe_ratio: 34.4544,
      company_market_cap: 1344402773825.4395,
      company_dividend_yield: 0.3793,
      wikipedia_url: "https://en.wikipedia.org/wiki/Meta_Platforms",
      google_mid: "/m/0rz9htl",
    },
  },
  TSLA: {
    data: {
      symbol: "TSLA:NASDAQ",
      name: "Tesla Inc",
      type: "stock",
      price: 164.9,
      open: 169.08,
      high: 170.86,
      low: 160.51,
      volume: 143157603,
      previous_close: 171.11,
      change: -6.21,
      change_percent: -3.6292,
      pre_or_post_market: 171.19,
      pre_or_post_market_change: 6.29,
      pre_or_post_market_change_percent: 3.8144,
      last_update_utc: "2024-04-06 00:30:00",
      country_code: "US",
      exchange: "NASDAQ",
      exchange_open: "2024-04-05 09:30:00",
      exchange_close: "2024-04-05 16:00:00",
      timezone: "America/New_York",
      utc_offset_sec: -14400,
      currency: "USD",
      about:
        "Tesla, Inc. is an American multinational automotive and clean energy company headquartered in Austin, Texas, which designs, manufactures and sells electric vehicles, stationary battery energy storage devices from home to grid-scale, solar panels and solar shingles, and related products and services.\nTesla was incorporated in July 2003 by Martin Eberhard and Marc Tarpenning as Tesla Motors. The company's name is a tribute to inventor and electrical engineer Nikola Tesla. In February 2004 Elon Musk joined as the company's largest shareholder and in 2008 he was named CEO. In 2008, the company began production of its first car model, the Roadster sports car, followed by the Model S sedan in 2012, the Model X SUV in 2015, the Model 3 sedan in 2017, the Model Y crossover in 2020, the Tesla Semi truck in 2022 and the Cybertruck pickup truck in 2023. The Model 3 is the all-time bestselling plug-in electric car worldwide, and in June 2021 became the first electric car to sell 1 million units globally. In 2023, the Model Y was the best-selling vehicle, of any kind, globally.\nTesla is one of the world's most valuable companies in terms of market capitalization.",
      year_low: 152.37,
      year_high: 299.29,
      primary_exchange: "NASDAQ",
      company_website: "https://www.tesla.com/",
      company_ceo: "Elon Musk",
      company_employees: 140473,
      company_founded_date: "2003-07-01",
      avg_volume: 77260222,
      company_pe_ratio: 38.3144,
      company_market_cap: 516709183874.8169,
      wikipedia_url: "https://en.wikipedia.org/wiki/Tesla,_Inc.",
      google_mid: "/m/0ckhqlx",
    },
  },
  MA: {
    data: {
      symbol: "MA:NYSE",
      name: "Mastercard Inc",
      type: "stock",
      price: 477.15,
      open: 474,
      high: 479.31,
      low: 472.53,
      volume: 2462740,
      previous_close: 469.77,
      change: 7.38,
      change_percent: 1.571,
      pre_or_post_market: 476.96,
      pre_or_post_market_change: -0.19,
      pre_or_post_market_change_percent: -0.0398,
      last_update_utc: "2024-04-06 00:04:00",
      country_code: "US",
      exchange: "NYSE",
      exchange_open: "2024-04-05 09:30:00",
      exchange_close: "2024-04-05 16:00:00",
      timezone: "America/New_York",
      utc_offset_sec: -14400,
      currency: "USD",
      about:
        "Mastercard Inc. is the second-largest payment-technology corporation worldwide. It offers a range of payment transaction processing and other related-payment services. Its headquarters are in Purchase, New York. Throughout the world, its principal business is to process payments between the banks of merchants and the card-issuing banks or credit unions of the purchasers who use the Mastercard-brand debit, credit and prepaid cards to make purchases. Mastercard has been publicly traded since 2006.\nMastercard was created by an alliance of several banks and regional bankcard associations in response to the BankAmericard issued by Bank of America, which later became Visa and is still its biggest competitor. Prior to its initial public offering, Mastercard Worldwide was a cooperative owned by the more than 25,000 financial institutions that issue its branded cards.",
      year_low: 355.97,
      year_high: 490,
      primary_exchange: "NYSE",
      company_website: "http://www.mastercard.com/",
      company_country_code: "US",
      company_country: "United States",
      company_state: "New York",
      company_city: "Purchase",
      company_street_address: "2000 Purchase Street",
      company_ceo: "Michael Miebach",
      company_employees: 33400,
      company_cdp_score: "A-",
      company_founded_date: "1966-11-03",
      company_cdp_url: "https://www.cdp.net/en/responses/11421",
      avg_volume: 1818139,
      company_pe_ratio: 40.3201,
      company_market_cap: 445129125816.0828,
      company_dividend_yield: 0.5533,
      wikipedia_url: "https://en.wikipedia.org/wiki/Mastercard",
      google_mid: "/m/07zkz18",
    },
  },
  NFLX: {
    data: {
      symbol: "NFLX:NASDAQ",
      name: "Netflix Inc",
      type: "stock",
      price: 636.18,
      open: 624.92,
      high: 637.91,
      low: 622.71,
      volume: 3378842,
      previous_close: 617.14,
      change: 19.04,
      change_percent: 3.0852,
      pre_or_post_market: 637.02,
      pre_or_post_market_change: 0.84,
      pre_or_post_market_change_percent: 0.132,
      last_update_utc: "2024-04-06 00:30:00",
      country_code: "US",
      exchange: "NASDAQ",
      exchange_open: "2024-04-05 09:30:00",
      exchange_close: "2024-04-05 16:00:00",
      timezone: "America/New_York",
      utc_offset_sec: -14400,
      currency: "USD",
      about:
        'Netflix is an American subscription video on-demand over-the-top streaming service. The service primarily distributes original and acquired films and television shows from various genres, and it is available internationally in multiple languages.\nLaunched on January 16, 2007, nearly a decade after Netflix, Inc. began its pioneering DVD‑by‑mail movie rental service, Netflix is the most-subscribed video on demand streaming media service, with 260.28 million paid memberships in more than 190 countries as of January 2024. By 2022, "Netflix Original" productions accounted for half of its library in the United States and the namesake company had ventured into other categories, such as video game publishing of mobile games via its flagship service. As of October 2023, Netflix is the 24th most-visited website in the world with 23.66% of its traffic coming from the United States, followed by the United Kingdom at 5.84% and Brazil at 5.64%.',
      year_low: 315.62,
      year_high: 638,
      primary_exchange: "NASDAQ",
      company_website: "https://www.netflix.com/",
      company_country_code: "US",
      company_country: "United States",
      company_state: "California",
      company_city: "Los Gatos",
      company_street_address: "100 Winchester Circle",
      company_ceo: "Greg Peters",
      company_employees: 13000,
      company_founded_date: "1997-08-29",
      avg_volume: 2432328,
      company_pe_ratio: 52.8776,
      company_market_cap: 275312999158.374,
      wikipedia_url: "https://en.wikipedia.org/wiki/Netflix",
      google_mid: "/m/07zm2vb",
    },
  },
  ACN: {
    data: {
      symbol: "ACN:NYSE",
      name: "Accenture Plc",
      type: "stock",
      price: 333,
      open: 331.53,
      high: 333.82,
      low: 330.33,
      volume: 3694783,
      previous_close: 330.47,
      change: 2.53,
      change_percent: 0.7656,
      pre_or_post_market: 330.1852,
      pre_or_post_market_change: -2.8148,
      pre_or_post_market_change_percent: -0.8453,
      last_update_utc: "2024-04-06 00:04:00",
      country_code: "US",
      exchange: "NYSE",
      exchange_open: "2024-04-05 09:30:00",
      exchange_close: "2024-04-05 16:00:00",
      timezone: "America/New_York",
      utc_offset_sec: -14400,
      currency: "USD",
      about:
        "Accenture plc is a US multinational professional services company based in Dublin, specializing in information technology services and consulting. A Fortune Global 500 company, it reported revenues of $64.1 billion in 2023. Accenture's current clients include 91 of the Fortune Global 100 and more than three-quarters of the Fortune Global 500. As of 2022, Accenture is considered the largest consulting firm in the world by number of employees.\nJulie Sweet has been CEO of Accenture since 1 September 2019.",
      year_low: 261.68,
      year_high: 387.51,
      primary_exchange: "NYSE",
      company_website: "http://www.accenture.com/",
      company_ceo: "Julie Sweet",
      company_employees: 742000,
      company_cdp_score: "A",
      company_founded_date: "1989-undefined-undefined",
      company_cdp_url: "https://www.cdp.net/en/responses/21318",
      avg_volume: 2081307,
      company_pe_ratio: 30.1838,
      company_market_cap: 223250459400,
      company_dividend_yield: 1.5495,
      wikipedia_url: "https://en.wikipedia.org/wiki/Accenture",
      google_mid: "/m/07zky97",
    },
  },
  CRM: {
    data: {
      symbol: "CRM:NYSE",
      name: "Salesforce Inc",
      type: "stock",
      price: 301.91,
      open: 293.54,
      high: 303.415,
      low: 293.295,
      volume: 4918179,
      previous_close: 294.14,
      change: 7.77,
      change_percent: 2.6416,
      pre_or_post_market: 301.8,
      pre_or_post_market_change: -0.11,
      pre_or_post_market_change_percent: -0.0364,
      last_update_utc: "2024-04-06 00:04:00",
      country_code: "US",
      exchange: "NYSE",
      exchange_open: "2024-04-05 09:30:00",
      exchange_close: "2024-04-05 16:00:00",
      timezone: "America/New_York",
      utc_offset_sec: -14400,
      currency: "USD",
      about:
        "Salesforce, Inc. is an American cloud-based software company headquartered in San Francisco, California. It provides customer relationship management software and applications focused on sales, customer service, marketing automation, e-commerce, analytics, and application development.\nFounded by former Oracle executive Marc Benioff in February 1999, Salesforce grew quickly, making its IPO in 2004. As of September 2022, Salesforce is the 61st largest company in the world by market cap with a value of nearly US$153 billion. It became the world's largest enterprise software firm in 2022. Salesforce ranked 491st on the 2023 edition of the Fortune 500, making $31,352 million in revenues. Since 2020, Salesforce has also been a component of the Dow Jones Industrial Average.",
      year_low: 187.31,
      year_high: 318.715,
      primary_exchange: "NYSE",
      company_website: "http://www.salesforce.com/",
      company_country_code: "US",
      company_country: "United States",
      company_state: "California",
      company_city: "San Francisco",
      company_street_address: "SALESFORCE TOWER",
      company_ceo: "Marc Benioff",
      company_employees: 72682,
      company_cdp_score: "A-",
      company_founded_date: "1999-02-undefined",
      company_cdp_url: "https://www.cdp.net/en/responses/16158",
      avg_volume: 5661847,
      company_pe_ratio: 71.8278,
      company_market_cap: 292248853353.9215,
      company_dividend_yield: 0.53,
      wikipedia_url: "https://en.wikipedia.org/wiki/Salesforce",
      google_mid: "/m/07zkzm3",
    },
  },
  WMT: {
    data: {
      symbol: "WMT:NYSE",
      name: "Walmart Inc",
      type: "stock",
      price: 59.85,
      open: 59.55,
      high: 60.04,
      low: 59.49,
      volume: 10335909,
      previous_close: 59.5,
      change: 0.35,
      change_percent: 0.5882,
      pre_or_post_market: 59.81,
      pre_or_post_market_change: -0.04,
      pre_or_post_market_change_percent: -0.0668,
      last_update_utc: "2024-04-06 00:04:00",
      country_code: "US",
      exchange: "NYSE",
      exchange_open: "2024-04-05 09:30:00",
      exchange_close: "2024-04-05 16:00:00",
      timezone: "America/New_York",
      utc_offset_sec: -14400,
      currency: "USD",
      about:
        "Walmart Inc. is an American multinational retail corporation that operates a chain of hypermarkets, discount department stores, and grocery stores in the United States, headquartered in Bentonville, Arkansas. The company was founded by brothers Sam and James \"Bud\" Walton in nearby Rogers, Arkansas in 1962 and incorporated under Delaware General Corporation Law on October 31, 1969. It also owns and operates Sam's Club retail warehouses.\nAs of October 31, 2022, Walmart has 10,586 stores and clubs in 24 countries, operating under 46 different names. The company operates under the name Walmart in the United States and Canada, as Walmart de México y Centroamérica in Mexico and Central America, and as Flipkart Wholesale in India. It has wholly owned operations in Chile and a majority stake in Massmart in South Africa. Since August 2018, Walmart held only a minority stake in Walmart Brasil, which was renamed Grupo Big in August 2019, with 20 percent of the company's shares, and private equity firm Advent International holding 80% ownership of the company.",
      year_low: 48.3366,
      year_high: 61.655,
      primary_exchange: "NYSE",
      company_website: "http://corporate.walmart.com/",
      company_country_code: "US",
      company_country: "United States",
      company_state: "Arkansas",
      company_city: "Bentonville",
      company_street_address: "702 SW 8th St",
      company_ceo: "Doug McMillon",
      company_employees: 2100000,
      company_cdp_score: "C",
      company_founded_date: "1962-07-02",
      company_cdp_url: "https://www.cdp.net/en/responses/20402",
      avg_volume: 16849663,
      company_pe_ratio: 31.2851,
      company_market_cap: 482274160504.3945,
      company_dividend_yield: 1.3868,
      wikipedia_url: "https://en.wikipedia.org/wiki/Walmart",
      google_mid: "/m/07zlm7d",
    },
  },
  V: {
    data: {
      symbol: "V:NYSE",
      name: "Visa Inc",
      type: "stock",
      price: 277.14,
      open: 276.1,
      high: 277.957,
      low: 275.03,
      volume: 4392050,
      previous_close: 274,
      change: 3.14,
      change_percent: 1.146,
      pre_or_post_market: 276.98,
      pre_or_post_market_change: -0.16,
      pre_or_post_market_change_percent: -0.0577,
      last_update_utc: "2024-04-06 00:04:00",
      country_code: "US",
      exchange: "NYSE",
      exchange_open: "2024-04-05 09:30:00",
      exchange_close: "2024-04-05 16:00:00",
      timezone: "America/New_York",
      utc_offset_sec: -14400,
      currency: "USD",
      about:
        "Visa Inc. is an American multinational payment card services corporation headquartered in San Francisco, California. It facilitates electronic funds transfers throughout the world, most commonly through Visa-branded credit cards, debit cards and prepaid cards. Visa is one of the world's most valuable companies.\nVisa does not issue cards, extend credit or set rates and fees for consumers; rather, Visa provides financial institutions with Visa-branded payment products that they then use to offer credit, debit, prepaid and cash access programs to their customers. In 2015, the Nilson Report, a publication that tracks the credit card industry, found that Visa's global network processed 100 billion transactions during 2014 with a total volume of US$6.8 trillion.\nVisa was founded in 1958 by Bank of America as the BankAmericard credit card program. In response to competitor Master Charge, BofA began to license the BankAmericard program to other financial institutions in 1966. By 1970, BofA gave up direct control of the BankAmericard program, forming a cooperative with the other various BankAmericard issuer banks to take over its management. It was then renamed Visa in 1976.",
      year_low: 216.14,
      year_high: 290.96,
      primary_exchange: "NYSE",
      company_website: "http://www.visa.com/",
      company_country_code: "US",
      company_country: "United States",
      company_state: "California",
      company_city: "San Francisco",
      company_street_address: "One Market Plaza",
      company_ceo: "Ryan McInerney",
      company_employees: 28800,
      company_cdp_score: "A",
      company_founded_date: "1958-09-18",
      company_cdp_url: "https://www.cdp.net/en/responses/22867",
      avg_volume: 4700839,
      company_pe_ratio: 35.1277,
      company_market_cap: 556765143808.2275,
      company_dividend_yield: 0.7505,
      wikipedia_url: "https://en.wikipedia.org/wiki/Visa_Inc.",
      google_mid: "/m/07zm01p",
    },
  },
  JPM: {
    data: {
      symbol: "JPM:NYSE",
      name: "JPMorgan Chase & Co",
      type: "stock",
      price: 197.45,
      open: 196.16,
      high: 198.1224,
      low: 195.11,
      volume: 6532278,
      previous_close: 195.65,
      change: 1.8,
      change_percent: 0.92,
      pre_or_post_market: 197.65,
      pre_or_post_market_change: 0.2,
      pre_or_post_market_change_percent: 0.1013,
      last_update_utc: "2024-04-06 00:04:00",
      country_code: "US",
      exchange: "NYSE",
      exchange_open: "2024-04-05 09:30:00",
      exchange_close: "2024-04-05 16:00:00",
      timezone: "America/New_York",
      utc_offset_sec: -14400,
      currency: "USD",
      about:
        "JPMorgan Chase & Co. is an American multinational financial institution headquartered in New York City and incorporated in Delaware. It is the largest bank in the United States and the world's largest bank by market capitalization as of 2023. As the largest of Big Four banks, the firm is considered systemically important by the Financial Stability Board. Its size and scale have often led to enhanced regulatory oversight as well as the maintenance of an internal \"Fortress Balance Sheet\" of capital reserves. The firm is headquartered at 383 Madison Avenue in Midtown Manhattan and is set to move into the under-construction JPMorgan Chase Building at 270 Park Avenue in 2025.\nThe firm's early history can be traced to 1799, with the founding of what became the Chase Manhattan Company. In 1871, J.P. Morgan & Co. was founded by J. P. Morgan who launched the House of Morgan on 23 Wall Street as a national purveyor of commercial, investment, and private banking services. The present company was formed after the two predecessor firms merged in 2000, creating a diversified holding entity.",
      year_low: 126.22,
      year_high: 200.94,
      primary_exchange: "NYSE",
      company_website: "http://www.jpmorganchase.com/",
      company_country_code: "US",
      company_country: "United States",
      company_state: "New York",
      company_city: "New York",
      company_street_address: "270 Park Avenue",
      company_ceo: "Jamie Dimon",
      company_employees: 309926,
      company_founded_date: "2000-12-31",
      company_cdp_url: "https://www.cdp.net/en/responses/9871",
      avg_volume: 6464719,
      company_pe_ratio: 12.1674,
      company_market_cap: 568778607659.0424,
      company_dividend_yield: 2.3297,
      wikipedia_url: "https://en.wikipedia.org/wiki/JPMorgan_Chase",
      google_mid: "/m/07zmchf",
    },
  },
};

module.exports = stockdata;
